sudo: required
services:
  - docker

before_install: 
  - docker build -f Dockerfile.dev -t actsaifurmurad001/docker-react .

script: 
  - docker run -e CI=true actsaifurmurad001/docker-react npm run testsss

